# Data Preprocessing

In [22]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('https://jetson-datathon-sample-data.s3.us-east-2.amazonaws.com/jetson-sample-data.csv')
df.date = pd.to_datetime(df.date)
df

,client_id,order_id,item_name,quantity,price,date
0,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Cosmonaut,1,16.0,2022-01-24
1,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Krombacher,1,8.0,2022-01-24
2,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Ahi Tuna,1,23.0,2022-01-24
3,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Little Gem Salad,1,14.0,2022-01-24
4,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,Fire Pie,1,20.0,2022-01-24
...,...,...,...,...,...,...
687906,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,HH Etta Rita,1,8.0,2021-11-16
687907,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,HH Negroni,1,8.0,2021-11-16
687908,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,Rack Roasted Oysters,1,14.0,2021-11-16
687909,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,Roasted Branzino,1,45.0,2021-11-16
687910,ahNzfnNldmVucm9vbXMtc2VjdXJlcicLEhpuaWdodGxvb3...,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,Brussels Sprouts,1,13.0,2021-11-16

In [24]:
result = df.groupby(['order_id','date'])['item_name'].apply(','.join).reset_index()

In [25]:
result['item_name'] = result['item_name'].apply(lambda x: x.split(','))

In [26]:
result

,order_id,date,item_name
0,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,2021-07-25,"[Mimosa Package, Fire Pie, Breakfast Sandwich,..."
1,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,2021-08-09,"[Focaccia, Iced Tea, Bubbling Shrimp, Hearth R..."
2,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,2021-08-14,"[sunset on damen, Margaritas For Everyone, Moc..."
3,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,2021-06-22,"[Well Tequila (Centenario Plata), Fire Pie, Pe..."
4,ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3...,2022-08-06,"[Lyre's Amalfi Spritz N/A, Focaccia, Grilled C..."
...,...,...,...
80512,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,2022-08-07,"[La Colombe Regular Coffee, Paloma Tequila, Br..."
80513,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,2022-08-07,"[Brunch Pepperoni Pizza, La Colombe Regular Co..."
80514,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,2022-08-09,"[Kids Lemonade, Etta Rita, Etta Old Fashioned,..."
80515,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,2022-08-07,"[Mimosa Package, Etta Soft Scramble, Crispy Po..."
80516,ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3...,2022-08-07,"[Avocado Toast, French Toast, The ""etta"" Chopp..."

# Popular Combos

In [27]:
import itertools

combinations_list = []
for row in result.item_name:
    combinations = list(itertools.combinations(row, 2))
    combinations_list.append(combinations)

In [28]:
combination_counts = pd.Series(combinations_list).explode().reset_index(drop=True)
combination_counts = combination_counts.value_counts().reset_index()
combination_counts.columns = ["Sets", "Count"]
combination_counts

                                                   Sets  Count
0                              (Guest Love, Guest Love)  25367
1                     (Focaccia, Bucatini Cacio e Pepe)   9213
2                                (Focaccia, Guest Love)   9112
3                                (Etta Rita, Etta Rita)   8942
4                       (Focaccia, Cavatelli Bolognese)   6183
...                                                 ...    ...
190469                  (Bushmills, Orange Phyllo Cake)      1
190470         (Marinated Tuscan Kale Salad, Bushmills)      1
190471                      (Chilled Oysters, Bailey's)      1
190472  (Black Truffle Pizza, GL Cirelli Montepulciano)      1
190473                  (Miller High Life, Picnic Sour)      1

[190474 rows x 2 columns]

In [29]:
popular = combination_counts.head(50)
popular

                                         Sets  Count
0                    (Guest Love, Guest Love)  25367
1           (Focaccia, Bucatini Cacio e Pepe)   9213
2                      (Focaccia, Guest Love)   9112
3                      (Etta Rita, Etta Rita)   8942
4             (Focaccia, Cavatelli Bolognese)   6183
5                 (Focaccia, Bubbling Shrimp)   5979
6               (Bubbling Shrimp, Guest Love)   5957
7                        (Focaccia, Pomodoro)   5673
8                 (Focaccia, Spicy Meatballs)   5597
9                   (Focaccia, Wild Mushroom)   5562
10                     (Focaccia, Margherita)   5172
11                    (Etta Rita, Guest Love)   4944
12             (Celebration Shot, Guest Love)   4863
13   (Spicy Meatballs, Bucatini Cacio e Pepe)   4756
14               (Focaccia, Celebration Shot)   4586
15   (Ricotta Pillows, Bucatini Cacio e Pepe)   4458
16                      (Etta Rita, Focaccia)   4402
17               (Focaccia, Little Gem Salad)   4358
18                (Focaccia, Ricotta Pillows)   4357
19   (Bubbling Shrimp, Bucatini Cacio e Pepe)   4332
20                     (Focaccia, Broccolini)   4142
21       (Focaccia, The "etta" Chopped Salad)   3860
22                           (Tito's, Tito's)   3842
23              (Spicy Meatballs, Guest Love)   3837
24              (Ricotta Pillows, Guest Love)   3759
25                      (Focaccia, Etta Rita)   3745
26        (Bucatini Cacio e Pepe, Guest Love)   3423
27     (Spicy Meatballs, Cavatelli Bolognese)   3396
28                         (Focaccia, Caesar)   3343
29         (Rack Roasted Oysters, Guest Love)   3329
30   (Etta Old Fashioned, Etta Old Fashioned)   3234
31         (Bubbling Shrimp, Spicy Meatballs)   3187
32                        (Focaccia, Burrata)   3178
33           (Bubbling Shrimp, Wild Mushroom)   2979
34                           (Mimosa, Mimosa)   2972
35         (Etta Rita, Bucatini Cacio e Pepe)   2929
36  (Little Gem Salad, Bucatini Cacio e Pepe)   2860
37             (Focaccia, Wood-Fired Chicken)   2844
38             (Guest Love, Celebration Shot)   2822
39   (etta Old Fashioned, etta Old Fashioned)   2775
40        (Focaccia, Crispy Chicken Sandwich)   2775
41               (Guest Love, Staff Discount)   2753
42                (Focaccia, Pepperoni Pizza)   2750
43     (Ricotta Pillows, Cavatelli Bolognese)   2739
44     (Bubbling Shrimp, Cavatelli Bolognese)   2725
45             (Etta Old Fashioned, Focaccia)   2722
46                       (Focaccia, Fire Pie)   2675
47              (Etta Rita, Celebration Shot)   2670
48  (Bucatini Cacio e Pepe, Celebration Shot)   2625
49               (Etta Rita, Bubbling Shrimp)   2537

In [30]:
import pickle
pickle.dump(popular, open('/content/popular','wb'))

# Combo Recommendation

In [31]:
df_temp = df.copy().drop(["client_id", "price", "date", "quantity"], axis=1)
onehot = df_temp.pivot_table(index='order_id', columns='item_name', aggfunc=len, fill_value=0)
onehot = onehot>0
onehot

item_name,Coffeee Cake,$10 N/A Bev Package,$10 Upcharge,$15 Upcharge,$2 Oysters,$2 Upcharge,$20 Kids Brunch,$25 Plated,$25 Upcharge,$3 Centennario Shot,...,how i like my coffee,lambrusco risotto,marinated olives,pappardelle,pig picnic pita,rack of lamb,smash burger,summer peppers,sunset on damen,whole dover sole
order_id,,,,,,,,,,,,,,,,,,,,,
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---TiRsM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY---jqRsM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6CghsM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6L6BoM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlciULEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwY--6_4h4M,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszuPA1AsM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszuPY7QkM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszubI0wgM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszv2iywoM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
ahNzfnNldmVucm9vbXMtc2VjdXJlcigLEhtuaWdodGxvb3BfUmVzZXJ2YXRpb25BY3R1YWwYgIDszvC57AgM,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# compute frequent items using the Apriori algorithm
frequent_itemsets = apriori(onehot, min_support = 0.001, max_len = 2, use_colnames=True)

# compute all association rules for frequent_itemsets
rules = association_rules(frequent_itemsets)
rules.sort_values('confidence', ascending=False).reset_index(drop=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Adult Mother's Day Brunch),(Banana Bread),0.001192,0.024566,0.001192,1.000000,40.706269,0.001163,inf
1,(Easter Steak),(Easter Crumb Bar),0.001279,0.001292,0.001279,1.000000,774.201923,0.001278,inf
2,(Easter Steak),(Easter French Toast),0.001279,0.001292,0.001279,1.000000,774.201923,0.001278,inf
3,(Easter Hearth Roast Lamb Leg),(Easter Market Greens),0.001143,0.001155,0.001143,1.000000,865.774194,0.001141,inf
4,(Easter Hearth Roast Lamb Leg),(Easter Pancakes),0.001143,0.001155,0.001143,1.000000,865.774194,0.001141,inf
...,...,...,...,...,...,...,...,...,...
295,(Dobel Shot),(Guest Love),0.002260,0.119366,0.002062,0.912088,7.641097,0.001792,10.017211
296,(Centenario Shot),(Guest Love),0.004955,0.119366,0.004397,0.887218,7.432747,0.003805,7.808287
297,(Macaron),(Celebration Shot),0.005092,0.090937,0.004484,0.880488,9.682360,0.004020,7.606443
298,(Ricotta),(Focaccia),0.001416,0.392253,0.001217,0.859649,2.191570,0.000662,4.330200
299,(Staff Discount),(Guest Love),0.010023,0.119366,0.008545,0.852540,7.142231,0.007348,5.972030

In [33]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift', 'leverage',
       'conviction'],
      dtype='object')

In [57]:
recommend = rules[['antecedents', 'consequents', 'confidence']].copy()

In [58]:
print(recommend)

                     antecedents                  consequents  confidence
0    (Adult Mother's Day Brunch)               (Banana Bread)    1.000000
1    (Adult Mother's Day Brunch)          (CCard Convenience)    0.968750
2    (Adult Mother's Day Brunch)                      (Fruit)    1.000000
3    (Adult Mother's Day Brunch)                   (MD Bacon)    0.968750
4                     (MD Bacon)  (Adult Mother's Day Brunch)    0.989362
..                           ...                          ...         ...
295                     (Turkey)            (Spicy Meatballs)    0.991597
296               (Thanksgiving)                     (Turkey)    0.991667
297                     (Turkey)               (Thanksgiving)    1.000000
298        (Thanksgiving Dinner)              (Turkey Picnic)    1.000000
299              (Turkey Picnic)        (Thanksgiving Dinner)    1.000000

[300 rows x 3 columns]

In [59]:
# Apply the function to the 'fset' column and convert to strings
recommend['antecedents'] = recommend['antecedents'].map(str)
recommend['consequents'] = recommend['consequents'].map(str)

In [60]:
# define the conversion function
def convert_str(val):
    if isinstance(val, str) and val.count("'") == 2:
        return val.replace("'", '"')
    else:
        return val

# apply the conversion function to all elements of the dataframe
recommend = recommend.applymap(convert_str)

In [61]:
recommend

,antecedents,consequents,confidence
0,"frozenset({""Adult Mother's Day Brunch""})","frozenset({""Banana Bread""})",1.000000
1,"frozenset({""Adult Mother's Day Brunch""})","frozenset({""CCard Convenience""})",0.968750
2,"frozenset({""Adult Mother's Day Brunch""})","frozenset({""Fruit""})",1.000000
3,"frozenset({""Adult Mother's Day Brunch""})","frozenset({""MD Bacon""})",0.968750
4,"frozenset({""MD Bacon""})","frozenset({""Adult Mother's Day Brunch""})",0.989362
...,...,...,...
295,"frozenset({""Turkey""})","frozenset({""Spicy Meatballs""})",0.991597
296,"frozenset({""Thanksgiving""})","frozenset({""Turkey""})",0.991667
297,"frozenset({""Turkey""})","frozenset({""Thanksgiving""})",1.000000
298,"frozenset({""Thanksgiving Dinner""})","frozenset({""Turkey Picnic""})",1.000000
299,"frozenset({""Turkey Picnic""})","frozenset({""Thanksgiving Dinner""})",1.000000

In [62]:
import re
pattern = r'frozenset\(\{?"(.*?)"?\}?\)'
recommend['antecedents'] = recommend['antecedents'].str.extract(pattern)
recommend['consequents'] = recommend['consequents'].str.extract(pattern)

In [63]:
recommend

                   antecedents                consequents  confidence
0    Adult Mother's Day Brunch               Banana Bread    1.000000
1    Adult Mother's Day Brunch          CCard Convenience    0.968750
2    Adult Mother's Day Brunch                      Fruit    1.000000
3    Adult Mother's Day Brunch                   MD Bacon    0.968750
4                     MD Bacon  Adult Mother's Day Brunch    0.989362
..                         ...                        ...         ...
295                     Turkey            Spicy Meatballs    0.991597
296               Thanksgiving                     Turkey    0.991667
297                     Turkey               Thanksgiving    1.000000
298        Thanksgiving Dinner              Turkey Picnic    1.000000
299              Turkey Picnic        Thanksgiving Dinner    1.000000

[300 rows x 3 columns]

In [71]:
pickle.dump(recommend.to_dict(), open('/content/recommend_dict','wb'))

# Streamlit Integration

In [65]:
!pip install streamlit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting streamlit
  Downloading streamlit-1.21.0-py2.py3-none-any.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 67.3 MB/s eta 0:00:00
Collecting blinker>=1.0.0
  Downloading blinker-1.6-py3-none-any.whl (13 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from streamlit) (2.8.2)
Collecting watchdog
  Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 KB 12.3 MB/s eta 0:00:00
Collecting gitpython!=3.1.19
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 KB 24.3 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from streamlit) (1.22.4)
Requirement already satisfied: pandas<2,>=0.25 in /usr/local/lib/python3.9/dist-packages (from streamlit) (1.4.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (13.3.3)
Collecting validators>=0.2
  Downloading validators-0.20.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: altair<5,>=3.2.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (4.2.2)
Requirement already satisfied: tornado>=6.0.3 in /usr/local/lib/python3.9/dist-packages (from streamlit) (6.2)
Requirement already satisfied: requests>=2.4 in /usr/local/lib/python3.9/dist-packages (from streamlit) (2.27.1)
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 KB 22.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.10.0.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (4.5.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (8.1.3)
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.8.0-py2.py3-none-any.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 88.2 MB/s eta 0:00:00
Requirement already satisfied: tzlocal>=1.1 in /usr/local/lib/python3.9/dist-packages (from streamlit) (4.3)
Requirement already satisfied: pyarrow>=4.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (9.0.0)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.9/dist-packages (from streamlit) (6.1.0)
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (5.3.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/dist-packages (from streamlit) (8.4.0)
Requirement already satisfied: toml in /usr/local/lib/python3.9/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: protobuf<4,>=3.12 in /usr/local/lib/python3.9/dist-packages (from streamlit) (3.20.3)
Requirement already satisfied: packaging>=14.1 in /usr/local/lib/python3.9/dist-packages (from streamlit) (23.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.9/dist-packages (from altair<5,>=3.2.0->streamlit) (3.1.2)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.9/dist-packages (from altair<5,>=3.2.0->streamlit) (0.4)
Requirement already satisfied: toolz in /usr/local/lib/python3.9/dist-packages (from altair<5,>=3.2.0->streamlit) (0.12.0)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.9/dist-packages (from altair<5,>=3.2.0->streamlit) (4.3.3)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 9.0 MB/s eta 0:00:00
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=1.4->streamlit) (3.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas<2,>=0.25->streamlit) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil->streamlit) (1.16.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests>=2.4->streamlit) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.4->streamlit) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.4->streamlit) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.4->streamlit) (1.26.15)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.9/dist-packages (from rich>=10.11.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.9/dist-packages (from rich>=10.11.0->streamlit) (2.14.0)
Requirement already satisfied: pytz-deprecation-shim in /usr/local/lib/python3.9/dist-packages (from tzlocal>=1.1->streamlit) (0.1.0.post0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.9/dist-packages (from validators>=0.2->streamlit) (4.4.2)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2->altair<5,>=3.2.0->streamlit) (2.1.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema>=3.0->altair<5,>=3.2.0->streamlit) (22.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.9/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=10.11.0->streamlit) (0.1.2)
Requirement already satisfied: tzdata in /usr/local/lib/python3.9/dist-packages (from pytz-deprecation-shim->tzlocal>=1.1->streamlit) (2023.3)
Building wheels for collected packages: validators
  Building wheel for validators (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=3188d9d7820cb878a8960bc229f9f8b1751c0bd0cf0cc3e5821216e282fa31d9
  Stored in directory: /root/.cache/pip/wheels/2d/f0/a8/1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built validators
Installing collected packages: watchdog, validators, smmap, pympler, blinker, pydeck, gitdb, gitpython, streamlit
Successfully installed blinker-1.6 gitdb-4.0.10 gitpython-3.1.31 pydeck-0.8.0 pympler-1.0.1 smmap-5.0.0 streamlit-1.21.0 validators-0.20.0 watchdog-3.0.0

In [101]:
%%writefile app.py
import streamlit as st
import pickle
import altair as alt
import pandas as pd

popular_upload = pickle.load(open('/content/popular', 'rb'))
recommend_dict = pickle.load(open('/content/recommend_dict', 'rb'))
recommend_upload = pd.DataFrame(recommend_dict)
new_df = pd.concat([recommend_upload['antecedents'], recommend_upload['consequents']], ignore_index=True)

st.title('YumMatch :yum:')

st.header('Food Recommender System')
option = st.selectbox(
    'Finding Something Yummy?',
    new_df.unique()
)
if st.button('Recommend'):
    st.table(recommend_upload.loc[recommend_upload['antecedents'] == option])
    st.table(recommend_upload.loc[recommend_upload['consequents'] == option])

st.header('Popular Combos')
st.table(popular_upload)

st.header('Summary')
st.markdown('- Prepocessed a dataset that had client_id, order_id, item_name, quantity, price & date with 687911 entries.')
st.markdown('- Depending on the order_id and the date, we found out that what are the meals that are eaten together.')
st.markdown('- Depending on the above data, we found the data for the most popular meal combos.')
st.markdown('- With the help of Association Rules using Apriori, we found out that what meals will the customers like to have together.')
st.markdown('- We then deployed the app with the help of streamlit using localtunnel (Used colab because too many iterations were incompatible with the local GPU)')

Overwriting app.py

In [100]:
!streamlit run app.py & npx localtunnel --port 8501

[#######...........] / extract:localtunnel: verb lock using /root/.npm/_locks/s
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

npx: installed 22 in 2.193s

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.12:8501
  External URL: http://34.126.98.231:8501

your url is: https://gentle-heads-wave-34-126-98-231.loca.lt
  Stopping...
^C